apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-secrets-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default
roleRef:
  kind: ClusterRole
  name: jenkins-secrets-clusterrole
  apiGroup: rbac.authorization.k8s.io
