backend:
  image:
    repository: avishilon22/backend
    tag: latest
  service:
    type: ClusterIP
    port: 5000
  env:
    - name: DATABASE_URL
      value: postgresql://backend:backend@db:5432/tasks

frontend:
  image:
    repository: nginxinc/nginx-unprivileged
    tag: 1.27-alpine
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 8087
    targetPort: 80

database:
  image:
    repository: postgres
    tag: "15"
  service:
    type: ClusterIP
    port: 5432
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: tasks
