apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: {{ .Values.database.service.type }}
  selector:
    app: db
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 5432
