apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ include "database.name" . }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 5432
      name: postgres
  selector:
    app: {{ include "database.name" . }}
