apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "database.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "database.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "database.name" . }}
    spec:
      containers:
        - name: {{ include "database.name" . }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          ports:
            - containerPort: 5432
              name: postgres
          env:
            {{- with .Values.database.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 5432
          readinessProbe:
            tcpSocket:
              port: 5432
