apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |-
    {{ .Files.Get "files/index.html" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |-
    {{ .Files.Get "files/default.conf" | indent 4 }}
