apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Values.frontend.configMap.nginxConfigMap }}


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ include "frontend.fullname" . }}
#   labels:
#     {{- include "frontend.labels" . | nindent 4 }}
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       serviceAccountName: {{ include "frontend.serviceAccountName" . }}
#       containers:
#         - name: frontend
#           image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
#           ports:
#             - containerPort: 80
#           volumeMounts:
#             - name: frontend-html
#               mountPath: /usr/share/nginx/html
#             - name: nginx-conf
#               mountPath: /etc/nginx/conf.d
#               readOnly: false
#           livenessProbe:
#             httpGet:
#               path: {{ .Values.livenessProbe.httpGet.path }}
#               port: {{ .Values.livenessProbe.httpGet.port }}
#           readinessProbe:
#             httpGet:
#               path: {{ .Values.readinessProbe.httpGet.path }}
#               port: {{ .Values.readinessProbe.httpGet.port }}
#       volumes:
#         - name: frontend-html
#           configMap:
#             name: "frontend-html"
#         - name: nginx-conf
#           configMap:
#             name: "nginx-config"
